# Generated by Django 5.2.6 on 2025-11-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_areadoconhecimento_post_area_do_conhecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadoconhecimento',
            name='color',
            field=models.CharField(default='#3498db', help_text='HEX color, e.g. #3498db', max_length=7),
        ),
    ]
