# Generated by Django 5.2.6 on 2025-11-27 17:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_areadoconhecimento_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadoconhecimento',
            name='color',
            field=colorfield.fields.ColorField(default='#3498db', help_text='Choose a color', image_field=None, max_length=25, samples=None),
        ),
    ]
