# Generated by Django 5.2.6 on 2025-11-27 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dificuldade_post_updated_at_post_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dificuldade',
            name='color',
            field=colorfield.fields.ColorField(default='#3498db', help_text='Choose a color', image_field=None, max_length=25, samples=None),
        ),
    ]
